import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import { describe, expect, test } from "vitest";

const run = promisify(execFile);
const assembler = fileURLToPath(
  new URL("../scripts/consolidate-laurels.mjs", import.meta.url),
);

describe("laurel consolidation", () => {
  test("renders every seat from both event streams without rankings or totals", async () => {
    const root = await mkdtemp(join(tmpdir(), "fortkit-laurels-"));
    await Promise.all([
      mkdir(join(root, "fort", "events"), { recursive: true }),
      mkdir(join(root, "civ", "events"), { recursive: true }),
    ]);
    await Promise.all([
      writeFile(
        join(root, "fort", "events", "events-2026-08-30.jsonl"),
        [
          '{"ts":"2026-08-30T22:00:00Z","actor":"mayor","category":"laurel","target":"forge","detail":"Built the instrument","payload":{"citation":"fortkit-35uf.3","conferring_actor":"overseer"}}',
          '{"ts":"2026-08-30T21:00:00Z","actor":"warden","category":"laurel","target":"forge","detail":"Earlier recognition","payload":{"citation":"review:123"}}',
        ].join("\n"),
      ),
      writeFile(
        join(root, "civ", "events", "events-2026-08-30.jsonl"),
        '{"ts":"2026-08-30T23:00:00Z","actor":"chronicler","category":"laurel","target":"warden","detail":"Recorded a finding","payload":{"citation":"fortkit-x"}}\n',
      ),
    ]);

    await run(process.execPath, [assembler, root]);

    const forge = await readFile(
      join(root, "fort", "laurels", "forge.md"),
      "utf8",
    );
    expect(forge).toContain(
      "Generated by `scripts/consolidate-laurels.mjs`; do not edit.",
    );
    expect(forge).toContain("conferred by overseer; citation: fortkit-35uf.3");
    expect(forge).toContain("conferred by warden; citation: review:123");
    expect(forge.indexOf("Built the instrument")).toBeLessThan(
      forge.indexOf("Earlier recognition"),
    );
    expect(forge).not.toMatch(/count|total|rank|most laurelled/iu);
    expect(
      await readFile(join(root, "fort", "laurels", "warden.md"), "utf8"),
    ).toContain("Recorded a finding");
    for (const seat of [
      "chronicler",
      "herald",
      "mayor",
      "regent",
      "researcher",
    ])
      await expect(
        readFile(join(root, "fort", "laurels", `${seat}.md`), "utf8"),
      ).resolves.toContain(`# Laurels: ${seat}`);
  });

  test("orders by parsed instant rather than its daily shard filename", async () => {
    const root = await mkdtemp(join(tmpdir(), "fortkit-laurels-utc-"));
    await mkdir(join(root, "fort", "events"), { recursive: true });
    await Promise.all([
      writeFile(
        join(root, "fort", "events", "events-2026-08-30.jsonl"),
        '{"ts":"2026-08-30T23:24:00-08:00","actor":"overseer","category":"laurel","target":"forge","detail":"Next UTC day despite this shard","payload":{"citation":"utc-pin"}}\n',
      ),
      writeFile(
        join(root, "fort", "events", "events-2026-08-31.jsonl"),
        '{"ts":"2026-08-31T06:00:00Z","actor":"overseer","category":"laurel","target":"forge","detail":"Earlier UTC instant despite next shard","payload":{"citation":"earlier"}}\n',
      ),
    ]);

    await run(process.execPath, [assembler, root]);

    const forge = await readFile(
      join(root, "fort", "laurels", "forge.md"),
      "utf8",
    );
    expect(forge.indexOf("Next UTC day despite this shard")).toBeLessThan(
      forge.indexOf("Earlier UTC instant despite next shard"),
    );
  });
});
