#!/usr/bin/env node
import { mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { DatabaseSync } from "node:sqlite";

const root = process.argv[2] ?? process.cwd();
const memory = join(root, "fort", "memory");
const factsDirectory = join(memory, "facts");
const current = join(memory, "current.md");
const index = join(memory, "index.db");

function fact(text, path) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/u.exec(text);
  if (match === null) return null;
  const frontmatter = Object.fromEntries([...match[1].matchAll(/^([a-z-]+):\s*(.*)$/gmu)].map(([, key, value]) => [key, value === "null" ? null : value.replace(/^"|"$/gu, "")]));
  const provenance = /^provenance:\s*\r?\n((?:\s+.+\r?\n?)+)/mu.exec(match[1])?.[1] ?? "";
  for (const [, key, value] of provenance.matchAll(/^\s+([a-z-]+):\s*(.*)$/gmu)) frontmatter[key] = value.replace(/^"|"$/gu, "");
  return { ...frontmatter, body: match[2].trim(), path };
}
function section(text, heading) {
  const match = new RegExp(`^##\\s+${heading}\\s*\\r?\\n([\\s\\S]*?)(?=^##\\s+|\\s*$)`, "mu").exec(text);
  return match?.[1].trim() ?? "";
}
function handoffStamp(text, fallback) {
  const heading = /^# Handoff: .+? (\S+)/mu.exec(text)?.[1];
  const instant = heading === undefined ? NaN : Date.parse(heading);
  return Number.isNaN(instant) ? fallback : instant;
}

async function files(directory, extension) {
  try { return (await readdir(directory)).filter((file) => file.endsWith(extension)).sort(); } catch { return []; }
}
async function build() {
  const rows = [];
  const factFiles = await files(factsDirectory, ".md");
  const facts = [];
  for (const file of factFiles) {
    const path = join(factsDirectory, file);
    const parsed = fact(await readFile(path, "utf8"), relative(root, path));
    if (parsed !== null) facts.push(parsed);
    if (parsed !== null) rows.push({ source: parsed.path, ts: parsed.date ?? "", actor: parsed["declared-by"] ?? "", seat: "", snippet: parsed.body });
  }
  const lines = ["# Manyhalls current operational truth", "", "_Generated by `scripts/consolidate-memory.mjs`; do not edit. Every item links to its source._", "", "## Core facts", ""];
  for (const item of facts.filter((item) => item.status === "active" && item.tier === "core").sort((a, b) => a.key.localeCompare(b.key))) lines.push(`- ${item.body.replaceAll("\n", " ")} — [${item.path}](${item.path})`);

  const beadsPath = join(root, ".beads", "issues.jsonl");
  const open = [];
  try {
    for (const line of (await readFile(beadsPath, "utf8")).split(/\r?\n/u)) {
      if (line.trim() === "") continue;
      const bead = JSON.parse(line);
      if (["open", "in_progress", "blocked"].includes(bead.status) && typeof bead.id === "string") open.push(bead);
      if (typeof bead.id === "string") rows.push({ source: ".beads/issues.jsonl", ts: bead.updated_at ?? "", actor: bead.assignee ?? "", seat: "", snippet: `${bead.id}: ${bead.title ?? ""}` });
    }
  } catch { /* disclosed in the index gaps table */ }
  lines.push("", "## Open work", "", ...open.sort((a, b) => a.id.localeCompare(b.id)).map((bead) => `- ${bead.id} [${bead.status}]: ${bead.title ?? "(untitled)"} — [${bead.id}](bead:${bead.id})`));

  const handoffDirectory = join(root, "fort", "handoffs");
  const newest = new Map();
  for (const file of await files(handoffDirectory, ".md")) {
    const match = /^([a-z0-9_-]+)-\d{4}-\d{2}-\d{2}/iu.exec(file); if (match === null) continue;
    const path = join(handoffDirectory, file); const text = await readFile(path, "utf8"); const stamp = handoffStamp(text, 0);
    const old = newest.get(match[1]); if (old === undefined || stamp > old.stamp || (stamp === old.stamp && file > old.file)) newest.set(match[1], { file, text, stamp });
    for (const heading of ["State of work", "Next actions"]) { const body = section(text, heading); if (body) rows.push({ source: relative(root, path), ts: new Date(stamp).toISOString(), actor: "", seat: match[1], snippet: body }); }
  }
  lines.push("", "## Latest handoffs", "");
  for (const [seat, handoff] of [...newest].sort(([a], [b]) => a.localeCompare(b))) for (const heading of ["State of work", "Next actions"]) { const body = section(handoff.text, heading); if (body) lines.push(`- ${seat} — ${heading}: ${body.replaceAll("\n", " ")} — [fort/handoffs/${handoff.file}](fort/handoffs/${handoff.file})`); }

  const eventsDirectory = join(root, "fort", "events"); const unresolved = [];
  for (const file of await files(eventsDirectory, ".jsonl")) for (const line of (await readFile(join(eventsDirectory, file), "utf8")).split(/\r?\n/u)) { try { const event = JSON.parse(line); if (event.category === "incident" && !/resolved|closed/iu.test(event.detail ?? "")) unresolved.push({ event, file }); rows.push({ source: `fort/events/${file}`, ts: event.ts ?? "", actor: event.actor ?? "", seat: event.seat ?? "", snippet: event.detail ?? "" }); } catch {} }
  lines.push("", "## Unresolved incidents", "", ...unresolved.sort((a, b) => String(a.event.ts).localeCompare(String(b.event.ts))).map(({ event, file }) => `- ${event.detail ?? "incident"} — [fort/events/${file}](fort/events/${file})`), "");
  await mkdir(memory, { recursive: true });
  const temp = `${current}.tmp`; await writeFile(temp, `${lines.join("\n")}\n`, "utf8"); await rename(temp, current);
  await rm(index, { force: true });
  const db = new DatabaseSync(index);
  db.exec("DROP TABLE IF EXISTS source; DROP TABLE IF EXISTS gaps; CREATE VIRTUAL TABLE source USING fts5(source, ts, actor, seat, snippet); CREATE TABLE gaps (source TEXT PRIMARY KEY, reason TEXT NOT NULL);");
  const insert = db.prepare("INSERT INTO source VALUES (?, ?, ?, ?, ?)");
  for (const row of rows) insert.run(row.source, row.ts, row.actor, row.seat, row.snippet);
  const gap = db.prepare("INSERT INTO gaps VALUES (?, ?)");
  for (const source of ["fort/annals", "interactions.jsonl"]) gap.run(source, "missing or not configured");
  db.close();
}
await build();
