#!/usr/bin/env node
import {
  mkdir,
  readdir,
  readFile,
  rename,
  stat,
  writeFile,
} from "node:fs/promises";
import { join, relative } from "node:path";

const root = process.argv[2] ?? process.cwd();
const seats = [
  "chronicler",
  "forge",
  "herald",
  "mayor",
  "regent",
  "researcher",
  "warden",
];

function compare(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

async function exists(path) {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function files(directory) {
  if (!(await exists(directory))) return [];
  const entries = await readdir(directory, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".jsonl"))
    .map((entry) => join(directory, entry.name))
    .sort(compare);
}

function citation(payload) {
  if (payload === null || typeof payload !== "object" || Array.isArray(payload))
    return null;
  return typeof payload.citation === "string" ? payload.citation : null;
}

function conferrer(event) {
  const payload = event.payload;
  if (
    payload !== null &&
    typeof payload === "object" &&
    !Array.isArray(payload) &&
    typeof payload.conferring_actor === "string"
  )
    return payload.conferring_actor;
  return typeof event.actor === "string" ? event.actor : "unknown";
}

async function laurels() {
  const records = new Map(seats.map((seat) => [seat, []]));
  for (const directory of [
    join(root, "fort", "events"),
    join(root, "civ", "events"),
  ]) {
    for (const path of await files(directory)) {
      const text = await readFile(path, "utf8");
      for (const [lineNumber, line] of text.split(/\r?\n/u).entries()) {
        if (line.trim() === "") continue;
        let event;
        try {
          event = JSON.parse(line);
        } catch {
          continue;
        }
        if (event.category !== "laurel" || !records.has(event.target)) continue;
        const instant = Date.parse(event.ts);
        if (Number.isNaN(instant)) continue;
        records.get(event.target).push({
          instant,
          ts: event.ts,
          detail:
            typeof event.detail === "string"
              ? event.detail
              : "laurel conferred",
          conferrer: conferrer(event),
          citation: citation(event.payload),
          source: `${relative(root, path)}:${lineNumber + 1}`,
        });
      }
    }
  }
  return records;
}

function render(seat, records) {
  const lines = [
    `# Laurels: ${seat}`,
    "",
    "_Generated by `scripts/consolidate-laurels.mjs`; do not edit. Events are newest first._",
    "",
  ];
  for (const record of records.sort(
    (left, right) =>
      right.instant - left.instant || compare(right.source, left.source),
  )) {
    const citationText = record.citation ?? "citation absent";
    lines.push(
      `- ${record.ts} — ${record.detail} (conferred by ${record.conferrer}; citation: ${citationText}) — [source](${record.source})`,
    );
  }
  return lines.join("\n");
}

async function build() {
  const output = join(root, "fort", "laurels");
  await mkdir(output, { recursive: true });
  for (const [seat, records] of await laurels()) {
    const path = join(output, `${seat}.md`);
    const temp = `${path}.tmp`;
    await writeFile(temp, render(seat, records), "utf8");
    await rename(temp, path);
  }
}

await build();
